version: "3.8"
services:
  app:
    image: thread-docker
    container_name: node-server
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/thread
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
